<template>
  <div id="wrapper">
    <div
      id="main-ui-wrapper"
      style="padding-top: 0.5em; padding-bottom: 0.5em"
      class="container-fluid"
    >
      <div id="main-ui" class="main-panel border shadow-sm rounded">
        <img id="logo" alt="iNFT" src="./assets/inft_logo.svg" />
        <hr style="margin-bottom: 0.5em" />

        <a
          href="#collapseIndicatorChevronDark"
          v-b-toggle.collapse-about
          @click.prevent
          class="text-center"
          style="display: block"
          id="headingExampleTwoDark"
          data-bs-toggle="collapse"
          aria-expanded="false"
          aria-controls="collapseIndicatorChevronDark"
        >
          About
          <b-icon-chevron-down class="when-closed" />
          <b-icon-chevron-up class="when-open" />
        </a>
        <b-collapse id="collapse-about">
          <p>
            iNFT is an NFT that can be generated by validated identities in
            Idena.
          </p>
          <p>
            An identity can only generate one iNFT, and it can be regenerated to
            update its look and stats (looks change once per epoch).
          </p>
        </b-collapse>

        <Identity :identity="identity" @signOut="signOut" @signIn="signIn" />
        <div>
          <div v-if="waitingForReceipt != null">
            <hr />
            <div class="text-center animated-underline">
              Waiting for
              <a :href="waitingForReceiptLink" target="_blank">{{
                waitingForReceiptShortHash
              }}</a>
            </div>
          </div>
          <button
            v-if="canMint && waitingForReceipt == null"
            class="btn btn-primary"
            style="width: 100%; margin-top: 1rem"
            @click="sendGenerateTx"
          >
            <div
              v-if="generating"
              class="load-spinner spinner-border spinner-border-sm"
              role="status"
            >
              <span class="sr-only">Generating...</span>
            </div>
            <div v-else>Generate</div>
          </button>
        </div>
      </div>

      <div
        v-if="inft.balance != 0"
        id="owned-panel"
        class="main-panel border shadow-sm rounded"
      >
        <h3 class="text-center" style="margin-bottom: 0">Owned</h3>
        <hr style="margin-top: 0" />
        <div
          v-if="inft.tokensOwned.length == 0"
          class="load-spinner spinner-border spinner-border"
        ></div>
        <div v-else v-for="tokenId in inft.tokensOwned" :key="tokenId">
          <iNFT
            :tokenId="tokenId"
            :tokenUris="inft.tokenUris"
            :tokenPngs="inft.tokenPngs"
            :isOwned="true"
            :generators="artGenerators"
            :selectedGenerator="selectedGenerator"
            @regenerate="sendRegenerateTx"
            @transfer="sendTransferTx"
            @burn="sendBurnTx"
            @selectGenerator="setGenerator"
            @refreshMetadata="refreshURI"
          />
          <hr
            v-if="
              inft.tokensOwned.indexOf(tokenId) != inft.tokensOwned.length - 1
            "
          />
        </div>
      </div>
      <div id="owned-panel" class="main-panel border shadow-sm rounded">
        <h3 class="text-center" style="margin-bottom: 0">Recently minted</h3>
        <hr style="margin-top: 0" />
        <div
          v-if="inft.recentlyMinted.length == 0"
          class="load-spinner spinner-border spinner-border"
        ></div>
        <div v-else v-for="tokenId in inft.recentlyMinted" v-bind:key="tokenId">
          <iNFT
            :tokenId="tokenIdToHex(tokenId)"
            :tokenUris="inft.tokenUris"
            :tokenPngs="inft.tokenPngs"
            :isOwned="false"
            :generators="artGenerators"
            :selectedGenerator="selectedGenerator"
            @refreshMetadata="refreshURI"
            @seeOwner="openTokenOwner"
          />
          <hr
            v-if="
              inft.recentlyMinted.indexOf(tokenId) !=
              inft.recentlyMinted.length - 1
            "
          />
        </div>
        <button
          v-if="
            tokenIdToHex(inft.recentlyMinted[inft.recentlyMinted.length - 1]) !=
            '0x0100000000000000'
          "
          class="btn btn-light"
          style="width: 100%; margin-top: 1rem"
          @click="fetchRecentlyMinted(5)"
        >
          Load more
        </button>
      </div>
      <div id="footer" class="text-center">
        <div class="me">
          Made by <a href="https://github.com/busimus/inft">bus</a>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import Identity from "./components/Identity.vue";
import { default as iNFT, rasterize } from "./components/iNFT.vue";
import { Conn } from "./connection.js";
import { randomBytes } from "crypto";
import {
  bufferToHex,
  ecrecover,
  toBuffer,
  fromRpcSig,
  keccak256,
  pubToAddress,
  isValidAddress,
  intToBuffer,
} from "ethereumjs-util";
import { Buffer } from "buffer";
import { openDB } from "idb";
import { BN } from "bn.js";
import { argsToSlice } from "./utils.js";
import { BCollapse, BIconChevronDown, BIconChevronUp } from "bootstrap-vue";
import {
  INFT_CONTRACT,
  ART_GENERATORS,
  CALLBACK_URL,
  NODE_URL,
  NODE_KEY,
  AUTH_WORKER_URL,
} from "./config.js";

import * as proto from "./proto/models_pb.js";

const STATES_CAN_MINT = ["Newbie", "Verified", "Human"];
const ZERO_TOKEN = "0x0000000000000000";

const dbPromise = openDB("inft", 1, {
  upgrade(db) {
    try {
      db.createObjectStore("tokenUris");
      db.createObjectStore("tokenPngs");
    } catch (e) {
      console.error("Error creating object store", e);
    }
  },
});

export default {
  name: "App",
  components: {
    Identity,
    iNFT,
    BCollapse,
    BIconChevronDown,
    BIconChevronUp,
  },
  data: function () {
    const conn = new Conn(this.connected, NODE_URL, NODE_KEY);

    const address = null;
    // const address = "0x00000000c911117a28a5f3e87c37d4c914c9b80a";
    // localStorage.address = address;
    return {
      conn,
      address,
      identity: { state: "Undefined", address: address },
      epoch: 0,
      generating: false,
      inft: {
        balance: 0,
        minted: "",
        tokensOwned: [],
        tokenUris: {},
        tokenPngs: {},
        recentlyMinted: [],
      },
      artGenerators: ART_GENERATORS,
      selectedGenerator: "iNFT 1.0",
      waitingForReceipt: null,
    };
  },
  methods: {
    signIn: function () {
      this.signOut();
      const token = "tk-" + randomBytes(12).toString("hex");

      const url = `https://app.idena.io/dna/signin
?callback_url=${CALLBACK_URL}signin?token=${token}
&token=${token}
&nonce_endpoint=${AUTH_WORKER_URL}%2FgetToken
&authentication_endpoint=${AUTH_WORKER_URL}%2Fauthenticate`;
      window.open(url, "_blank");
    },
    fetchSignature: async function (token) {
      const response = await fetch(
        "https://workers.bus.bz/idena/auth/getSignature",
        {
          method: "POST",
          mode: "cors",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ token }),
        }
      );
      const data = await response.json();
      console.log("data", data);
      return data.signature;
    },
    recoverAddress: function (signature) {
      const nonce = "signin-uwu";
      const nonceHash = keccak256(keccak256(Buffer.from(nonce, "utf-8")));
      const { v, r, s } = fromRpcSig(signature);
      const pubKey = ecrecover(nonceHash, v, r, s);
      const addrBuf = pubToAddress(pubKey);
      const addr = bufferToHex(addrBuf);
      return addr;
    },
    signOut: function () {
      history.pushState("", document.title, "/");
      this.address = null;
      this.identity = { state: "Undefined", address: null };
      this.inft.balance = 0;
      this.inft.minted = null;
      this.inft.tokensOwned = [];
      localStorage.removeItem("address");
    },
    sendGenerateTx: async function () {
      const args = [
        {
          index: 0,
          format: "hex",
          value: ART_GENERATORS[this.selectedGenerator].toString(),
        },
      ];
      await this.buildTx("generate", args);
    },
    sendRegenerateTx: async function (args) {
      const argsArray = [
        {
          index: 0,
          format: "hex",
          value: args.tokenId,
        },
        {
          index: 1,
          format: "hex",
          value: ART_GENERATORS[this.selectedGenerator].toString(),
        },
      ];
      await this.buildTx("regenerate", argsArray);
    },
    sendTransferTx: async function (args) {
      const argsArray = [
        {
          index: 0,
          format: "hex",
          value: this.address,
        },
        {
          index: 1,
          format: "hex",
          value: args.to,
        },
        {
          index: 2,
          format: "hex",
          value: args.tokenId,
        },
      ];
      await this.buildTx("transferFrom", argsArray);
    },
    sendBurnTx: async function (args) {
      const argsArray = [
        {
          index: 0,
          format: "hex",
          value: args.tokenId,
        },
      ];
      await this.buildTx("burn", argsArray);
    },
    buildTx: async function (method, args) {
      this.generating = true;
      console.log(method, args);
      try {
        const balance = await this.conn.getBalance(this.address);
        const nonce = balance.nonce + 1;
        // const nonce = 1;
        console.log(nonce, this.epoch);
        const payload = proto.encodeProtoCallContractAttachment({
          method,
          args: argsToSlice(args),
        });
        console.log(payload);
        console.log(bufferToHex(payload));
        const maxFee = new BN("10000000000000000000");
        const maxFeeBytes = toBuffer(maxFee);

        const tx = proto.encodeProtoTransaction({
          data: {
            type: 16,
            to: INFT_CONTRACT.buf,
            maxFee: maxFeeBytes,
            nonce: nonce,
            epoch: this.epoch,
            payload: payload,
          },
        });
        const serialized = bufferToHex(tx);
        console.log("serialized", serialized);
        const url = `https://app.idena.io/dna/raw?tx=${serialized}
        &callback_url=${CALLBACK_URL}${method}`;
        window.open(url, "_blank");
      } catch (e) {
        console.error(e);
      }
      this.generating = false;
    },
    waitForReceipt: async function (hash) {
      this.waitingForReceipt = hash;
      while (true) {
        try {
          const receipt = await this.conn.getTxReceipt(hash);
          if (receipt) {
            this.waitingForReceipt = null;
            return receipt;
          }
        } catch (e) {
          console.error(e);
        }
        await new Promise((resolve) => setTimeout(resolve, 2000));
      }
    },
    initAddress: async function () {
      console.log("initAddress");
      if (this.address) {
        console.log("address", this.address);
        this.identity = await this.conn.getIdentity(this.address);
        // this.identity.state = "Human";
        // this.identity.address = this.address;
        this.inft.balance = await this.conn.getTokenBalance(this.address);
        this.inft.minted = await this.conn.getMintedBy(this.address);
        this.epoch = (await this.conn.getEpoch()).epoch;
        // this.epoch = 0;
        if (this.inft.balance > 0) {
          this.inft.tokensOwned = await this.conn.getTokensOwnedBy(
            this.address,
            this.inft.balance
          );
          await this.fetchTokenUris(this.inft.tokensOwned);
        } else {
          this.inft.tokensOwned = [];
        }
      }
    },
    fetchTokenUris: async function (tokenIds, force = false) {
      for (const tokenId of tokenIds) {
        let tokenUri = await this.getFromCache("tokenUris", tokenId);
        let tokenPng = await this.getFromCache("tokenPngs", tokenId);

        if (
          tokenUri == null ||
          tokenPng == null ||
          tokenUri == "null" ||
          force
        ) {
          console.warn("uncached tokenUri", tokenId, tokenUri);
          tokenUri = await this.conn.getTokenURI(tokenId);
          tokenPng = await rasterize(tokenUri);
          await this.storeInCache("tokenUris", tokenId, tokenUri);
          await this.storeInCache("tokenPngs", tokenId, tokenPng);
        }
        this.$set(this.inft.tokenPngs, tokenId, tokenPng);
        this.$set(this.inft.tokenUris, tokenId, tokenUri);
      }
    },
    fetchRecentlyMinted: async function (amount = 5) {
      let supply = await this.conn.readCall("totalSupply");
      console.log("supply", supply, "amount", amount);
      const buf = Buffer.from(supply.slice(2), "hex").reverse();
      supply = parseInt(buf.toString("hex"), 16);
      console.log("supplyNum", supply);
      let lastRecentId =
        this.inft.recentlyMinted[this.inft.recentlyMinted.length - 1] ||
        supply + 1;
      console.log("lastRecentId", lastRecentId);
      for (let i = 0; i < amount; i++) {
        const tokenId = lastRecentId - 1;
        if (tokenId <= 0) {
          break;
        }
        const tokenIdHex = this.tokenIdToHex(tokenId);
        console.log("tokenId", tokenId, tokenIdHex);
        // TODO: Check for burn
        await this.fetchTokenUris([tokenIdHex]);
        this.inft.recentlyMinted.push(tokenId);
        lastRecentId = tokenId;
      }
    },
    openTokenOwner: async function (tokenId) {
      const owner = await this.conn.getTokenOwner(tokenId);
      window.open(`https://scan.idena.io/identity/${owner}`, "_blank");
    },
    setGenerator(name) {
      this.selectedGenerator = name;
    },
    refreshURI: async function (tokenId) {
      await this.fetchTokenUris([tokenId], true);
    },
    tokenIdToHex(tokenId) {
      if (typeof tokenId !== "number") {
        return null;
        // tokenId = parseInt(tokenId, 16);
      }
      return (
        "0x" + intToBuffer(tokenId).reverse().toString("hex").padEnd(16, "0")
      );
    },
    onStorageUpdate(event) {
      if (event.key === "address") {
        console.log("storage update", event.newValue);
        this.address = event.newValue;
      }
    },
    getFromCache: async function (store, key) {
      try {
        return await (await dbPromise).get(store, key);
      } catch (e) {
        console.error("Error while getting from cache:", e);
        return null;
      }
    },
    storeInCache: async function (store, key, value) {
      try {
        await (await dbPromise).put(store, value, key);
      } catch (e) {
        console.error("Error while storing in cache:", e);
      }
    },
  },
  mounted() {
    if (localStorage.address != null) {
      console.log("address in storage", localStorage.address);
      if (isValidAddress(localStorage.address) == false) {
        console.warn("Invalid address in storage!");
        this.signOut();
        return;
      }
      this.address = localStorage.address;
    }
    window.addEventListener("storage", this.onStorageUpdate);
    this.fetchRecentlyMinted();
  },
  beforeDestroy() {
    window.removeEventListener("storage", this.onStorageUpdate);
  },
  watch: {
    address(newAddress) {
      console.log("watch newAddress", newAddress);
      if (isValidAddress(newAddress) == false) {
        console.warn("Invalid address!");
        this.signOut();
        return;
      }
      localStorage.address = newAddress;
      this.initAddress();
    },
  },
  computed: {
    canMint: function () {
      if (!this.address) {
        return false;
      }
      if (STATES_CAN_MINT.indexOf(this.identity.state) == -1) {
        return false;
      }
      if (this.inft.minted == null || this.inft.minted != ZERO_TOKEN) {
        return false;
      }
      return true;
    },
    waitingForReceiptLink() {
      return `https://scan.idena.io/transaction/${this.waitingForReceipt}`;
    },
    waitingForReceiptShortHash() {
      // leave only first 4 and last 4 chars
      const shortHash =
        this.waitingForReceipt.slice(0, 6) +
        ".." +
        this.waitingForReceipt.slice(-4);
      return shortHash;
    },
  },
  created: async function () {
    const url = new URLSearchParams(window.location.search);
    const path = location.pathname.slice(1);
    if (path == "signin") {
      const token = url.get("token");
      console.log("sign in", token);
      if (!token) {
        console.error("No token");
        return;
      }
      const signature = await this.fetchSignature(token);
      localStorage.address = this.recoverAddress(signature);
      this.address = localStorage.address;
      history.pushState("", document.title, "/");
    } else if (path == "reset" || path == "resetAll") {
      localStorage.clear();
      this.signOut();
      if (path == "resetAll") {
        await (await dbPromise).clear("tokenUris");
        await (await dbPromise).clear("tokenPngs");
      }
      history.pushState("", document.title, "/");
    } else if (path) {
      console.log("got path", path);
      const txHash = url.get("tx");
      if (!txHash) {
        console.error("No TX hash");
        return;
      }
      const receipt = await this.waitForReceipt(txHash);
      history.pushState("", document.title, "/");
      if (receipt.success == false) {
        console.error("TX failed", receipt);
        return;
      }
      if (path == "generate" || path == "regenerate") {
        let tokenId = null;
        for (const event of receipt.events) {
          if (event.event == "GeneratedArt") {
            tokenId = event.args[1];
            console.log("generated", tokenId);
          } else if (
            event.event == "Transfer" &&
            event.args[1] == this.address
          ) {
            tokenId = event.args[2];
            this.inft.tokensOwned.push(tokenId);
            console.log("transferred", tokenId);
            break;
          }
        }
        if (tokenId == null || tokenId == ZERO_TOKEN) {
          console.error("Failed to get tokenId", tokenId);
          return;
        }
        await this.fetchTokenUris([tokenId], true);
        this.inft.balance = await this.conn.getTokenBalance(this.address);
        this.inft.minted = await this.conn.getMintedBy(this.address);
      } else if (path == "transferFrom" || path == "burn") {
        if (receipt.success) {
          this.inft.balance -= 1;
          const transferArgs = receipt.events[0].args;
          if (transferArgs[1] != this.address.toString()) {
            this.inft.tokensOwned = this.inft.tokensOwned.filter(
              (token) => token != transferArgs[2]
            );
          }
        }
      }
    }
  },
  destroyed: function () {
    console.log("destroyed");
    this.conn.stop();
  },
};
</script>

<style>
* {
  font-family: Helvetica;
  box-sizing: border-box;
}

#wrapper {
  width: 100%;
  height: 100%;
  display: flex;
}

#main-ui-wrapper {
  margin-top: auto;
  margin-bottom: auto;
  max-width: 20rem;
  /* width: 100%; */
  padding: 0;
}

.main-panel {
  padding: 1rem 1rem 1em 1em;
  background-color: white;
  margin-bottom: 0.5em;
}

#logo {
  width: 100%;
}

#footer {
  margin-top: 0.7rem;
  color: #777;
}

#footer .me {
  font-size: 0.65rem;
  color: #666;
}

#footer a {
  color: #666;
}

#footer .address {
  font-size: 0.55rem;
}

.ceremony-state {
  font-size: 0.9rem;
}

.eligibilityAlert {
  margin-bottom: 0;
}

.load-spinner {
  display: flex;
  justify-content: center;
  align-items: center;
  margin: auto;
}

/* Define the animation keyframes */
@keyframes loading-underline {
  0% {
    left: 0;
    width: 0;
  }
  50% {
    left: 0;
    width: 100%;
  }
  100% {
    left: 100%;
    width: 0;
  }
}

/* Create the CSS class for the animated underline */
.animated-underline {
  position: relative;
  padding-bottom: 0.5em;
  /* display: inline-block; */
}

/* Add the pseudo-element and apply the animation */
.animated-underline::after {
  content: "";
  position: absolute;
  margin-top: 0.5em;
  bottom: 0;
  left: 0;
  width: 0;
  height: 2px; /* Adjust the underline thickness as needed */
  background-color: #6c757d;
  animation: loading-underline 1s cubic-bezier(0.445, 0.05, 0.55, 0.95) infinite;
}

.collapsed > .when-open,
.not-collapsed > .when-closed {
  display: none;
}

body,
html {
  width: 100%;
  height: 100%;
  background-color: #f0f0f0;
}
</style>
